// application.js
import "@rails/activestorage"
import "@rails/actiontext"
import "bootstrap"
import "trix"
import "@rails/actiontext"
import "@hotwired/turbo-rails"
import "./controllers"
import "./charts"
